name = "chat-server"
main = "src/worker.ts"
compatibility_date = "2023-08-21"

[[kv_namespaces]]
binding = "CHAT_KV"
id = "abf2d475b9f74d4bb4e67defcdf97e12"
preview_id = "c677a03ad5334e89b16e01bbcbfb58fd"

[[durable_objects.bindings]]
name = "CHAT_DO"
class_name = "ChatServer"
